name: continuous integration
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
    branches:
      - main
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the dev branch
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'NBISweden/DNAharvester') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.10.3"
          #- "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Download EAGER test data
        run: |
          git clone --single-branch --branch eager https://github.com/nf-core/test-datasets.git data/eager

      - name: Run pipeline with EAGER test data
        run: |
         nextflow run ${GITHUB_WORKSPACE} -c .github/test-eager_github.config -profile test,docker --outdir ./eager-results
